name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches:
      - 'main'

env:
  PROJECT_ID: 'project-37ca8556-4c5d-47bd-9fd'
  REGION: 'us-central1'
  SERVICE: 'mi-app'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/807177859654/locations/global/workloadIdentityPools/github-pool/providers/github-provider'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@692973e3d937129bcbf40652eb
